services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: birthdayuser
      POSTGRES_PASSWORD: birthdaypass
      POSTGRES_DB: birthdaydb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: